### ISSUE TITLE
Basic Setup

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/Argon#1]
create a basic setup with Django==2.0.1 and add home into it.

**Comment by jaysoni-india** [comment]
Add me as well

**Comment by shivamsoftwareartist** [comment]
I want to create this setup.

**Comment by GouravSardana** [comment]
Okay @shivamsoftwareartist and @thenethead  create the setup and make a pull. Make sure you pull into a different branch.

**Comment by shivamsoftwareartist** [comment]
@GouravSardana What should be the name of Django setup? Should I just name it 'Argon'? and
 'home' should be an app or a template 'home.html'?

**Comment by GouravSardana** [comment]
@shivamsoftwareartist the repo name is argon. So all the django files contain into it and the app name will be home.
