### ISSUE TITLE
Fixing Issues with Code

### ISSUE THREAD

**Issue by kaustubhgupta** [IndianOpenSourceFoundation/Argon#12]
# Description 

As soon as I forked the repo and started the server with command:

`
python manage.py runserver
`

this error prompted up:

`
  File "D:\Projects\Argon\home\urls.py", line 9, in <module>
    path('admin/', admin.site.urls),
NameError: name 'admin' is not defined
`

I fixed the error and proceeded with other inspections. So I ran the test using the command:

`
python manage.py test
`

And got the following results:

```
Creating test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
```

# Proposed Solutions

- For the first issue, the home app needs to configured properly
- For the test issue, all apps needed to be checked
- Automating the testing process as soon as someone makes the commit on GitHub repo using GitHub actions

# Assignee:
I would like to solve this issue under hacktoberfest.

**Comment by GouravSardana** [comment]
Go ahead @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@GouravSardana one query, currently the project is based in Django 2.0.1 and Django 3.1 is already out. I can replicate/upgrade the project in Django 3. Waiting for your approval!

**Comment by GouravSardana** [comment]
@kaustubhgupta Sure. You can change it to Django 3 & Make sure nothing will break !

Fow now - We are not maintaining argon. You can do you changes for Hacktober

**Comment by kaustubhgupta** [comment]
Great! will make a PR very soon!
