### ISSUE TITLE
signup

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/Argon#6]
we need a signup page with attributes email, username, password, confirm password.

**Comment by shivamsoftwareartist** [comment]
I have been working on CustomUser so should I used it here? or keep it on a basic level?

**Comment by GouravSardana** [comment]
Why are using custom user if you use inbuilt user for signup!
Keep it simple. So that all can understand the work flow

**Comment by shivamsoftwareartist** [comment]
okay
